### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 3.94 GiB total capacity; 2.65 GiB already allocated; 2.25 MiB free; 4.11 MiB cached)

### ISSUE THREAD

**Issue by forever1078** [kuangliu/pytorch-cifar#89]
```
Epoch: 0
Traceback (most recent call last):
  File "main.py", line 142, in <module>
    train(epoch)
  File "main.py", line 93, in train
    outputs = net(inputs)
  File "/home/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/.local/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/Documents/FL-code/dataset/pytorch-cifar/models/googlenet.py", line 87, in forward
    out = self.a4(out)
  File "/home/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/Documents/FL-code/dataset/pytorch-cifar/models/googlenet.py", line 51, in forward
    y3 = self.b3(x)
  File "/home/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/.local/lib/python3.5/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/.local/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 3.94 GiB total capacity; 2.65 GiB already allocated; 2.25 MiB free; 4.11 MiB cached)
```
pytorch version: 1.1.0

**Comment by tannnguyen** [comment]
You just don't have memory in your GPU. Try to reduce the batch size

**Comment by goldentimecoolk** [comment]
I have 4 TITAN Xp and change the batch size to 16. But when I use `PreActResNet101`, there is still CUDA out of memory. When I merely change this model to resnet_v1_101, the problem gone. Does anybody have the same problem?

**Comment by goldentimecoolk** [comment]
I got it. I noticed that I cropped the size as 448*448, and that was the reason. When I changed it as 32*32, there was little GPU memory used. But another problem comes. When I train resnet_v1_101 with 448*448 input size, GPU is half used. When I change it as `PreActResNet101`, GPU is not enough. Two models have almost the same number of params. So what's the problem?

**Comment by goldentimecoolk** [comment]
> I got it. I noticed that I cropped the size as 448*448, and that was the reason. When I changed it as 32*32, there was little GPU memory used. But another problem comes. When I train resnet_v1_101 with 448*448 input size, GPU is half used. When I change it as `PreActResNet101`, GPU is not enough. Two models have almost the same number of params. So what's the problem?

I know it. The first conv in version 1 is 7\*7 with stride 2, but this version is 3\*3 with stride 1. In addition, there is max pooling with stride 2 in version 1. But this version doesn't have it.

**Comment by Lornatang** [comment]
I submitted these bugs to PyTorch, and the advice I gave was to adjust the multithreading to 1.
